In [5]:
import numpy as np

file_path = '/home/hanbing/RotNIST/data/angle/0/train_label_0.npy'
data = np.load(file_path)
print(data)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [3]:
file_path = '/home/hanbing/RotNIST/data/angle/0/valid_data_0.npy'
data = np.load(file_path)
print(data.shape)

(10000, 1, 28, 28)


In [21]:
file_path = '/Users/liuhanbing/Desktop/code/RotNIST/data/angle/0/test_label_0.npy'
data = np.load(file_path)
print(data.shape)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [29]:
import logging
import random
import time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.distributions import Bernoulli
from model_cl_multitask import SDG, Predictor
from data import RotNISTDataLoader
import ot

def compute_distribution_discrepancy(representations1, representations2, device):
    m = ot.dist(representations1, representations2, metric='euclidean')
    m = m / m.max()
    n1 = representations1.shape[0]
    n2 = representations2.shape[0]
    a, b = torch.ones((n1,)) / n1, torch.ones((n2,)) / n2
    m, a, b = m.to(device), a.to(device), b.to(device)
    w_dist = ot.sinkhorn2(a, b, m, numItermax=10000, reg=0.01)
    return w_dist

In [2]:
import torch
feature1 = torch.rand(100, 10)
feature1.shape

torch.Size([100, 10])

In [31]:
feature2 = feature1

In [32]:
feature2 == feature1

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True,

In [33]:
d = compute_distribution_discrepancy(feature1, feature2, 'cpu')

In [34]:
d

tensor(1.2203e-12)